### ISSUE TITLE
SolverConnection.solver.SolverException: ERROR: Command set_end_string not recognized

### ISSUE THREAD

**Issue by rfripp2** [kuba97531/PioSolverConnection#1]
Hi, when i try to run the examples, i get the following error:

$ python runme.py /c/PioSOLVER/PioSOLVER-pro.exe /c/PioSOLVER/saves/AsQs3d.cfr 
Traceback (most recent call last):
  File "C:\Users\JUAN\Desktop\gto_test\runme.py", line 58, in <module>
    main()
  File "C:\Users\JUAN\Desktop\gto_test\runme.py", line 13, in main
    connection = Solver(solver=sys.argv[1])
  File "C:\Users\JUAN\Desktop\gto_test\SolverConnection\solver.py", line 23, in __init__
    self.wait_line("END")
  File "C:\Users\JUAN\Desktop\gto_test\SolverConnection\solver.py", line 57, in wait_line
    self.read_until(target)
  File "C:\Users\JUAN\Desktop\gto_test\SolverConnection\solver.py", line 69, in read_until
    raise SolverException(line)
SolverConnection.solver.SolverException: ERROR: Command set_end_string not recognized

The locations of the files it seems that they are correctly because i can autocomplete with TAB. 
The code is identical to the python on this repo, i didint add anithing else.
Any ideas what can be my issue? 
Thanks!

**Comment by rfripp2** [comment]
I also tried like this:

$ python runme.py C:\PioSOLVER\PioSOLVER-pro.exe C:\PioSOLVER\saves\9s6s4s.cfr
Traceback (most recent call last):
  File "C:\Users\JUAN\Desktop\PioSolverConnection\python_2_0\runme.py", line 56, in <module>
    main()
  File "C:\Users\JUAN\Desktop\PioSolverConnection\python_2_0\runme.py", line 12, in main
    connection = Solver(solver=sys.argv[1])
  File "C:\Users\JUAN\Desktop\PioSolverConnection\python_2_0\SolverConnection\solver.py", line 19, in __init__
    self.process = subprocess.Popen(
  File "C:\Users\JUAN\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\JUAN\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
